### PR TITLE
Sync develop and master branches

### PR DESCRIPTION
**Pull request by rojosnow**
##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

### CODE REVIEW

**Comment by eswarasai** [comment]
@rojosnow -- For merging `develop` into `master`, we follow the below process instead of PR --

- To push commits of develop into master, in the terminal follow the below steps :
`git checkout develop`
`git pull -r`
`git checkout master`
`git pull -r`
`git merge develop`
`git push origin master`

- To push commits of master into develop, in the terminal follow the below steps :
`git checkout master`
`git pull -r`
`git checkout develop`
`git pull -r`
`git rebase master`
`Fix any conflicts during the rebase by doing git add . & git rebase --continue`
`git push -f origin develop`

cc: @pelsasser

**Comment by rojosnow** [comment]
@eswarasai @pelsasser It looked like the branches were out of sync and that's why I re-merged. Not sure I understand the message here, https://github.com/MARKETProtocol/MARKET.js/tree/develop, `This branch is 4 commits ahead, 3 commits behind master.` The git templates were updated when I look at `git diff master develop`. That is still displayed after the merge.

I typically use the above but did it in Github. After following the commands, 

```
11:15 $ git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
rojo@rojo-mbp13 ~/projects/market/repos/MARKET.js [develop|✔]
11:18 $ git pull -r
Already up to date.
Current branch develop is up to date.
rojo@rojo-mbp13 ~/projects/market/repos/MARKET.js [develop|✔]
11:18 $ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
rojo@rojo-mbp13 ~/projects/market/repos/MARKET.js [master|✔]
11:18 $ git pull -r
Already up to date.
Current branch master is up to date.
rojo@rojo-mbp13 ~/projects/market/repos/MARKET.js [master|✔]
11:18 $ git merge develop
Merge made by the 'recursive' strategy.
rojo@rojo-mbp13 ~/projects/market/repos/MARKET.js [master ↑·5|✔]
```
That's not right. What am I missing?? reflog below...

```
11:19 $ git reflog
77fa361 (HEAD -> master) HEAD@{0}: merge develop: Merge made by the 'recursive' strategy.
b53cf24 (origin/master, origin/HEAD) HEAD@{1}: checkout: moving from develop to master
9020139 (origin/develop, develop) HEAD@{2}: checkout: moving from master to develop
b53cf24 (origin/master, origin/HEAD) HEAD@{3}: pull: Fast-forward
69730df HEAD@{4}: reset: moving to HEAD~5
cc39d47 HEAD@{5}: rebase -i (abort): updating HEAD
cc39d47 HEAD@{6}: rebase: aborting
12f47a9 HEAD@{7}: rebase -i (start): checkout HEAD~5
cc39d47 HEAD@{8}: merge develop: Merge made by the 'recursive' strategy.
b53cf24 (origin/master, origin/HEAD) HEAD@{9}: checkout: moving from develop to master
9020139 (origin/develop, develop) HEAD@{10}: checkout: moving from master to develop
b53cf24 (origin/master, origin/HEAD) HEAD@{11}: pull: Fast-forward
12f47a9 HEAD@{12}: checkout: moving from develop to master
9020139 (origin/develop, develop) HEAD@{13}: checkout: moving from master to develop
12f47a9 HEAD@{14}: pull: Fast-forward
dc36b8e HEAD@{15}: pull: Fast-forward
661722c HEAD@{16}: checkout: moving from develop to master
9020139 (origin/develop, develop) HEAD@{17}: commit: Update references in README.md to use npm run <script> and remove unneeded FAQ, remove placeholder comments in travis yaml since all is working.
f99225d HEAD@{18}: commit: Minor formatting updates to README.md, changed prettier options to --parser typescript.
7ecce06 HEAD@{19}: commit: Fix typos in README.md.
89bfef7 HEAD@{20}: rebase -i (finish): returning to refs/heads/develop
89bfef7 HEAD@{21}: rebase -i (squash): Refactor project structure.
fe17ece HEAD@{22}: rebase -i (squash): # This is a combination of 2 commits.
61e3d49 HEAD@{23}: rebase -i (start): checkout HEAD~3
898c7f6 HEAD@{24}: commit: Added test to increase coverage to 100%.
40a3d77 HEAD@{25}: commit: Include missing files.
61e3d49 HEAD@{26}: commit: Refactor project structure.
661722c HEAD@{27}: checkout: moving from master to develop
661722c HEAD@{28}: checkout: moving from develop to master
661722c HEAD@{29}: checkout: moving from master to develop
661722c HEAD@{30}: clone: from https://github.com/MARKETProtocol/MARKET.js.git
```

**Comment by eswarasai** [comment]
@rojosnow -- Do you mind if I revert this PR and take a look at what's the issue?

**Comment by rojosnow** [comment]
Sure. I'm working locally the other way now master ==> develop. Conflicts on travis.yml, package.json, and README.md. Something is out of sync.

**Comment by eswarasai** [comment]
@rojosnow -- Are you able to resolve the conflicts? I see what's the issue here. PR #2 is missing from the `develop` branch which is causing the conflict here. Let me know if you need any of my help here. Thanks!

**Comment by rojosnow** [comment]
Yup! Strange. Not sure how I could have created a pull request without pushing `develop`. In any case, I'll resolve the `master` ==> `develop` conflicts and put to `develop`. Thanks for your help!!

**Comment by eswarasai** [comment]
@rojosnow -- No problem.

For some weird reason, this commit is empty -- https://github.com/MARKETProtocol/MARKET.js/commit/b53cf244ac634506851b2ab46783275325f94a8a. I'd recommend hard resetting the `master` and then rebase onto `develop`. Below are the steps in order to do that.

`git checkout master`
`git reset --hard 12f47a9ca954c8c3adc317d89e8ccd99ffd5cfce`
`git checkout develop`
`git rebase master`

Once conflicts resolved, you need to force push on both `master` as well as `develop`.

**Pull request merged**
