### PR TITLE
test(Collateral.ts): Added tests to cover collateral.ts

### LINKED ISSUE #53: [Collateral] Create full test suite for all functions in Collateral.ts
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a dev I would like testing to know if I break something!

### Why Is this Needed?

*Summary*: Increased coverage across MARKET.js

### Description

*Type*: Feature

### Current Behavior
Limited testing for Collateral.ts functionality

### Expected Behavior
Near 100% coverage!

### Reproduction
`npm run test` after setting up test environment and running migrations (or use docker!)

### Solution

*Summary*: Create tests for Collateral.ts

### Definition of Done
Create Tests For
- depositCollateralAsync (note a call to ERC20.approve is needed, see other tests for examples)
  - call is successful
  - balance after deposit is correct
- getUserAccountBalanceAsync
- withdrawCollateralAsync
  - call is successful
  - balance after is correct
- settleAndCloseAsync
  - call fails
  - attempting to get this to work in testing is a bit beyond the scope here so can be ifnored for now.

## Bounty Hunters - please let us know your planned solution and time frame so we can approve.

### PR DESCRIPTION
**Pull request by subramanianv**
##### Description
Added tests for collateral.ts

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
Tests

##### Testing
Yes. Existing tests pass
##### Refers/Fixes
Fixes #53

### CODE REVIEW

**Comment by eswarasai** [comment]
@subramanianv -- Overall this is looking good to me except for the `package-lock.json`. Please remove the file from your commit. I'll let @pelsasser approve and merge the PR. Thanks for the quick turn around on this one :)

**Comment by subramanianv** [comment]
@eswarasai I removed package-lock.json

**Comment by pelsasser** [comment]
thanks @subramanianv - going to merge this and get you paid out! Appreciate the help here, and sorry about the CLA - we will get that squared away.

**Comment by pelsasser** [comment]
@subramanianv - please `submit work` on gitcoin and we can get the bounty amount released.

**Comment by subramanianv** [comment]
@pelsasser Yes. I'll do that once the ETH TX Fees come back to normal levels

**Pull request merged**
