### PR TITLE
integration test for Market

### PR DESCRIPTION
**Pull request by pfilippi24**
##### Description
Provide a test, that fails when Market from dist bundle can't be instantiated.

New test runs for npm scripts: "test:prod" and "test:integration" (only "test:prod" runs the build as a first step, though)
Doesn't run for "test", "test:watch"

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Testing
run `npm run test:prod` -> passes

Change src/contract_wrappers/ContractWrapper.ts
line 26 -> `import * as Decoder from 'ethereum-input-data-decoder';`
line 508 -> `const decoder = new Decoder.default(contractSetWrapper.marketCollateralPool.contractAbi);`

`npm run test` still passes
`npm run test:prod` fails

##### Refers/Fixes
Fixes: #110

### CODE REVIEW

**Comment by eswarasai** [comment]
@pfilippi24 -- Thanks for the PR. I have couple of changes that we'll be needing in order to merge this PR. 

- Can you remove `test:integration` from `package.json` and instead rename the file to `Build.test.ts`? I'd like to run this test as well along with the entire test suite and this should be the easiest way to ensure without needing to make any config changes.

- Can you add another test to check whether the build is working fine or not by calling one of the functions from the instantiated `Market` class? For example -- https://github.com/MARKETProtocol/MARKET.js/blob/develop/test/Market.test.ts#L44

- You can follow the same config as here because we don't need to pass the contract addresses while instantiating `Market` class -- https://github.com/MARKETProtocol/MARKET.js/blob/develop/test/Market.test.ts#L27

**Comment by pfilippi24** [comment]
1. The test needs the build step to run before it. Therefore I added it
only to prod tests. Are you sure you want to add buimding the lib's dist
folder on each regular test run? Especially on test:watch? This may slow
down the dev workflow a bit.

2. & 3. Will do it later today.

Eswara Sai <notifications@github.com> schrieb am Mo., 6. Aug. 2018, 05:48:

**Comment by pfilippi24** [comment]
@eswarasai 

About 3: If I try to instantiate Market without the contract addresses, I get:
`TypeError: fs.readFileSync is not a function`

**Comment by eswarasai** [comment]
1) Yeah, I agree with you. Makes sense to have it separated it out since it depends on the build. Let's leave it as it is then.

3) Ahh. In that case, leave the instantiation as it is. I'll fix the error on the `develop` and update the tests before pushing it to `master`. Thanks!

**Comment by eswarasai** [comment]
@pfilippi24 -- Can you change the way we import `fs` in [`Utils.ts`](https://github.com/MARKETProtocol/MARKET.js/blob/develop/src/lib/Utils.ts#L8) to the one below? This should fix the above error and doesn't need you to pass the contract addresses. Thanks!

`const fs = require('fs');`

**Comment by pfilippi24** [comment]
sure. I'll try it out.

Am Mo., 6. Aug. 2018 um 08:54 Uhr schrieb Eswara Sai <
notifications@github.com>:

**Comment by pfilippi24** [comment]
@eswarasai Pushed the suggested changes. The integration test now runs the whole test suite for Market.

**Pull request merged**
