### PR TITLE
Fix contracts locations

### PR DESCRIPTION
**Pull request by KennethAshley**
##### Description
This PR aims to solve the issue of not being able to location contracts

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
Contracts

##### Refers/Fixes
Fixes: #47

### CODE REVIEW

**Comment by pelsasser** [comment]
@KennethAshley - thanks! this looks great, can you sign the CLA and I will get this merged asap!

**Comment by eswarasai** [comment]
@KennethAshley -- Can you also update the `truffle` version here? -- https://github.com/MARKETProtocol/MARKET.js/blob/develop/Dockerfile#L5

@pelsasser  -- Is it really required to specify the version that needs to be installed or can we automatically install the latest version of truffle?

**Comment by pelsasser** [comment]
@eswarasai - it is.  If new version changes break existing functionality it isn't always obvious and we end up spending a lot of time debugging only to find out its a version / dependency issue.

**Comment by KennethAshley** [comment]
@eswarasai hmmm...there seems to be issues with signed the cla. This is the message i receive:

image

I'll try again in a bit.

**Comment by KennethAshley** [comment]
@pelsasser we merged this but did i need to add the truffle version to the Dockerfile?

**Comment by pelsasser** [comment]
I took care of it.  Was a tiny change and was just easier to knock it out.

**Pull request merged**
