### PR TITLE
Add collateralTokenName to ContractMetaData

### PR DESCRIPTION
**Pull request by perfectmak**
##### Description

This PR returns attempts to fetch the collateralTokenName from the collateralToken contract and return it as part of the ContractMetaData. If name is not found, it returns `Not Available`.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Affected core subsystem(s)
ContractMetaData

##### Refers/Fixes

Fixes: #174

### CODE REVIEW

**Comment by pelsasser** [comment]
@perfectmak - some build issues ;( 

will review code now.

**Comment by perfectmak** [comment]
Oops!, I didn't notice. I'll check to fix and update to force re-build

**Comment by perfectmak** [comment]
Yeah. True. It is worth trying the `symbol` too. I'll check for it.

**Comment by pelsasser** [comment]
@perfectmak looks great!

**Pull request merged**
