### PR TITLE
Expose static getOrderHash() and isValidSignature() functions

### PR DESCRIPTION
**Pull request by perfectmak**
##### Description

Exposes getOrderHash() and isValidSignature() as static functions on Market.js

Also removes the existing isValidSignatureAsync() function Market.js to prevent confusion to the user.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
Market.ts

##### Testing
Updated existing tests to use the now exposed static methods

##### Refers/Fixes

Fixes: #163

### CODE REVIEW

**Comment by perfectmak** [comment]
@rojosnow @pelsasser f5 on this PR :)

**Comment by pelsasser** [comment]
@perfectmak - what does `f5` mean?

**Comment by rojosnow** [comment]
Per my earlier comment, now I understand why you're removing the `Async` versions

**Comment by perfectmak** [comment]
@pelsasser F5 on the keyboard is used to refresh (especially in the browsers)

**Comment by pelsasser** [comment]
:+1: thanks for enlightening me!

**Pull request merged**
