### PR TITLE
Added skipVerifyContracts to MARKETProtocolConfig

### PR DESCRIPTION
**Pull request by eswarasai**
##### Description
Added `skipVerifyContracts` boolean to the `MARKETProtocolConfig` to avoid errors while trying to verify the contracts in `MARKET.js` while connected to local truffle within `dApp`

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes: #176

### CODE REVIEW

**Comment by eswarasai** [comment]
@pelsasser -- Yep. We need to commit the `package-lock.json` as well to keep track of which package got added/changed when, especially the internal dependencies versions.

The reason I've added `skipVerifyContracts` is that it's self explanatory that passing it's value `true` would skip the verification of contracts. `isVerifyContracts` didn't seem like much of self explanatory to me. I think the reason you're suggesting `isSkipVerifyContracts` to follow the pattern of boolean naming convention. Let me know what you decide, so that I can go ahead and update the name accordingly. Thanks!

**Comment by pelsasser** [comment]
@eswarasai - more specifically - without a change to the package dependencies I am not sure why there would be a commit to package-lock.json.  I understand why it is under version control ;)

Either version of the name for boolean works I think as long as we stick with the `isBoolean` convention.

Thanks!

**Comment by eswarasai** [comment]
@pelsasser -- Oops. Sorry 😅 The reason there's a change is that when we update the version in `package.json`, we might skip installing the packages again in order to update the `package-lock.json`. Also, depending on the machine, I think there'd always be a change in `package-lock.json`, not sure though.

Cool. I'll update the variable name to `isVerifyContracts` as well as the logic accordingly

**Comment by pelsasser** [comment]
Sounds great! thanks

**Pull request merged**
